"""
Step 6: Extract locations, events, and relationships from Odyssey text
(Samuel Butler translation) using Gemini.

One-off data-preparation script — not part of the live query agent, which
stays on the Gemini query agent per CLAUDE.md's LLM 供應商使用範圍 (the
extraction model is set separately below, per CLAUDE.md's stated split:
extraction uses gemini-3.1-flash-lite, the live query agent uses
gemini-3.6-flash).

Characters are referenced ONLY by the fixed `slug`s in
data/characters_canonical.json (upsert key shared with the Wikidata
pipeline). Locations and events are new in each pass, so they don't have
real MongoDB _ids yet: the model assigns temporary local ids (temp_id,
e.g. "loc_1", "event_1") and relationships reference those; a later
import step resolves temp_id -> real ObjectId before writing to MongoDB.

Runs one BATCH at a time (see BATCHES below), each with its own source
text / output file / order range / hand-curated location+event "floor"
list — NOT a single call across all books. Books 9-12's existing
data/extraction_gemini.json is the original, already-demo-verified batch
and is never regenerated by this script; new batches (Book 5, Books
21-24) get their own output files that scripts/import_to_mongodb.py
merges in alongside it, so expanding the dataset can't silently alter
data the flagship demo questions already depend on.

Usage: python scripts/extract_books.py <batch_name>
  batch_name one of: book5, books21-24
"""

import json
import os
import sys
from pathlib import Path
from typing import List, Literal, Optional

from dotenv import load_dotenv
from google import genai
from google.genai import types
from opencc import OpenCC
from pydantic import BaseModel

load_dotenv()

# Gemini is instructed to write Traditional Chinese, but LLMs don't reliably
# honor that distinction from Simplified — convert programmatically as a
# safety net rather than trusting the prompt alone. s2twp = Simplified ->
# Traditional with Taiwan-standard phrasing (not just character shapes).
_CC = OpenCC("s2twp")


def _to_traditional(obj):
    """Recursively convert every 'zh' string field in a nested dict/list to
    Traditional Chinese (Taiwan phrasing) via OpenCC."""
    if isinstance(obj, dict):
        return {
            k: (_CC.convert(v) if k == "zh" and isinstance(v, str) else _to_traditional(v))
            for k, v in obj.items()
        }
    if isinstance(obj, list):
        return [_to_traditional(item) for item in obj]
    return obj


DATA_DIR = Path(__file__).resolve().parent.parent / "data"
CANONICAL_PATH = DATA_DIR / "characters_canonical.json"

MODEL = "gemini-3.1-flash-lite"


class Bilingual(BaseModel):
    en: str
    zh: str


class ExtractedLocation(BaseModel):
    temp_id: str
    name: Bilingual
    description: Bilingual
    order: int
    book_chapter: str


class ExtractedEvent(BaseModel):
    temp_id: str
    name: Bilingual
    description: Bilingual
    location_temp_id: str
    order: int
    book_chapter: str
    source_excerpt: str
    character_slugs: List[str]


class ExtractedRelationship(BaseModel):
    from_ref: str
    from_type: Literal["character", "location", "event"]
    to_ref: str
    to_type: Literal["character", "location", "event"]
    relation: str
    description: Optional[Bilingual] = None


class UnmatchedCharacter(BaseModel):
    name_in_text: str
    note: str


class ExtractionResult(BaseModel):
    locations: List[ExtractedLocation]
    events: List[ExtractedEvent]
    relationships: List[ExtractedRelationship]
    unmatched_characters: List[UnmatchedCharacter]


def build_prompt(canonical_chars: list, book_text: str, book_label: str,
                  location_floor: str, event_floor: str,
                  order_note: str, extra_notes: str = "") -> str:
    char_list_lines = []
    for c in canonical_chars:
        aliases = f" (also called: {', '.join(c['aliases'])})" if c.get("aliases") else ""
        char_list_lines.append(f"- slug: \"{c['slug']}\" — {c['name_en']}{aliases}, type: {c['type']}")
    char_list = "\n".join(char_list_lines)

    return f"""You are extracting structured data from Homer's Odyssey, {book_label}
(Samuel Butler's 1900 English prose translation), for a knowledge-graph demo.

## Canonical character list (CLOSED SET — do not invent characters)
Every character reference in your output MUST use one of these exact slugs.
The text may use alternate names (e.g. "Ulysses" = Odysseus, "Neptune" = Poseidon,
"Jove"/"Jupiter" = Zeus, "Teiresias" = Tiresias, "the sun-god" = Helios,
"Mercury" = Hermes, "Minerva" = Athena, "Euryclea" = Eurycleia) — map them
to the correct slug.

{char_list}

If you encounter a named, narratively significant character who is NOT in this
list, do NOT invent a slug for them or silently drop them — add them to
`unmatched_characters` instead, with the name as it appears in the text and a
short note on their role. Minor unnamed crew members/suitors ("his men", "the
suitors" collectively) should just be omitted entirely — don't create entries
for them; only named suitors already in the canonical list (antinous,
eurymachus) get individual events/relationships, the rest of the suitors as a
group don't need separate tracking.

## What to extract

1. **locations** — each distinct place/setting in this text.
{location_floor}
   Assign each a `temp_id` like "loc_1", "loc_2", ... {order_note}

2. **events** — significant plot events. Do not compress or skip.
{event_floor}
   Assign `temp_id` like "event_1", "event_2", ... `order` follows the same
   sequence as locations (events and locations share one timeline).
   `location_temp_id` must reference a location's `temp_id` from this same
   extraction. `source_excerpt` is a short (1-3 sentence) VERBATIM quote from
   the English text that supports this event — used later to show "why the AI
   said this" citations. `character_slugs` lists every character (by slug)
   involved in or present at the event — this is the ONLY place participation
   is recorded, do not also create a relationship edge for it (see below).

3. **relationships** — edges between characters, and between events. Keep this
   list focused on narrative causality and character dynamics — NOT
   participation (that's `character_slugs` on the event) and NOT family ties.

   **Absolutely do NOT extract family/genealogical relationships** — no
   `SON_OF`, `FATHER_OF`, `MOTHER_OF`, `CHILD_OF`, `SIBLING_OF`, `MARRIED_TO`,
   or anything equivalent, even if the text states it explicitly. That data
   already exists from a separate Wikidata pipeline — adding it here creates
   duplicate edges. If you're unsure whether a relation is "family" vs
   "narrative", leave it out.

   What TO extract:
   - character-to-character narrative dynamics: e.g. ("odysseus", "BLINDS",
     "polyphemus"), ("poseidon", "ANTAGONIST_OF", "odysseus"), ("odysseus",
     "KILLS", "antinous") — use short, specific verb-style relation labels
     consistent with this style (existing ones in the graph: BLINDS, CAUSES,
     ANTAGONIST_OF — reuse those where they fit, or add a new one like KILLS
     following the same style, rather than a generic label)
   - event-to-event causality where the text makes it explicit
   - event-to-character causality where an event directly produces a
     character-level consequence (e.g. an event "CAUSES" a god's enmity),
     IN ADDITION to the character-level edge above — both are useful for
     different graph queries
   Do NOT create LOCATED_AT edges for events — that's already captured by
   `location_temp_id` on the event. Do NOT create PARTICIPATES_IN edges —
   that's already captured by `character_slugs` on the event.

{extra_notes}

## Output language
`name`/`description` fields need both `en` (concise, based on the English
text) and `zh` (natural Traditional Chinese translation/summary, not a
literal word-for-word translation — write for a Chinese-reading audience who
hasn't necessarily read Homer). `source_excerpt` stays in English only (it's
a direct quote).

## Source text ({book_label}, Samuel Butler translation)

{book_text}
"""


BATCHES = {
    "book5": dict(
        text_path=DATA_DIR / "raw" / "odyssey_butler_book5.txt",
        output_path=DATA_DIR / "extraction_gemini_book5.json",
        book_label="Book 5",
        # Off the adventure map (see CLAUDE.md's 目前進度 note on this
        # batch) — order values just need to be globally unique and
        # chronologically sensible, they don't drive any map display.
        location_floor="""   This is a short book — expect exactly ONE location: Calypso's island
   (Ogygia). Do not split it into multiple locations even though the book
   covers several beats there (Hermes's visit, the raft-building, departure) —
   those are separate EVENTS at this one location. `order` for this location
   is 11.""",
        event_floor="""   Cover at minimum:
   - Hermes delivering Zeus's order that Calypso must release Odysseus
   - Calypso releasing Odysseus and helping him build a raft
   - Poseidon spotting Odysseus at sea and sending a storm that wrecks the raft
   - Odysseus washing ashore, exhausted, on the coast of Phaeacia (Scheria)
   `order` starts at 18 and increases by 1 per event, in narrative sequence.""",
        order_note="`order` is 11 for this single location.",
        extra_notes="""## Continuity note
This is a standalone batch — Books 6-20 (Odysseus's welcome by the Phaeacians,
his journey home, and his disguised return to Ithaca) are NOT covered in this
demo's dataset. Don't reference them or assume the reader has that context;
extract only what this text itself describes.""",
    ),
    "books21-24": dict(
        text_path=DATA_DIR / "raw" / "odyssey_butler_books21-24.txt",
        output_path=DATA_DIR / "extraction_gemini_books21-24.json",
        book_label="Books 21-24",
        # ON the adventure map as a single capstone "homecoming" stop —
        # see CLAUDE.md's 目前進度 note on this batch for why it's
        # compressed into one location rather than several.
        location_floor="""   These four books all take place at Odysseus's own palace/estate in
   Ithaca (plus a brief scene at Laertes's farm in Book 24) — extract exactly
   ONE location covering all of it: "Return to the Palace of Ithaca" (or
   similar). Do not split it by book or by room — this location is a
   deliberate narrative capstone representing the story's ending, not a
   blow-by-blow map of the palace. `order` for this location is 12.""",
        event_floor="""   Cover at minimum, each as its own event:
   - The contest of the bow (only Odysseus can string it and shoot through
     the axe-heads)
   - The slaughter of the suitors, naming Antinous (killed first) and
     Eurymachus (killed second) specifically since they're in the canonical
     character list; the rest of the suitors can be referred to collectively
     in the description
   - The punishment of the disloyal servants, specifically Melanthius (the
     goatherd who sided with the suitors)
   - Penelope's recognition of Odysseus (the secret of their marriage bed)
   - Odysseus's reunion with his father Laertes
   - Athena brokering peace between Odysseus and the suitors' families,
     ending the poem
   `order` starts at 22 and increases by 1 per event, in narrative sequence.""",
        order_note="`order` is 12 for this single location.",
        extra_notes="""## Continuity note
This batch picks up after a gap — Books 6-20 (Odysseus's journey home from
Phaeacia and his disguised return to Ithaca) are NOT covered in this demo's
dataset. Don't reference that gap or assume the reader has that context;
extract only what this text itself describes. Odysseus is already in disguise
as a beggar at the start of this text — treat that as the given starting
situation.""",
    ),
}


def run_batch(batch_name: str):
    if batch_name not in BATCHES:
        raise SystemExit(f"Unknown batch {batch_name!r} — choose one of {list(BATCHES)}")
    cfg = BATCHES[batch_name]

    api_key = os.environ["GEMINI_API_KEY"]
    client = genai.Client(api_key=api_key)

    with open(CANONICAL_PATH, encoding="utf-8") as f:
        canonical_chars = json.load(f)
    with open(cfg["text_path"], encoding="utf-8") as f:
        book_text = f.read()

    prompt = build_prompt(
        canonical_chars, book_text, cfg["book_label"],
        cfg["location_floor"], cfg["event_floor"], cfg["order_note"],
        cfg.get("extra_notes", ""),
    )

    print(f"Calling {MODEL} for batch {batch_name!r} ({len(prompt)} chars prompt)...")
    response = client.models.generate_content(
        model=MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=ExtractionResult,
        ),
    )

    result: ExtractionResult = response.parsed
    result_dict = _to_traditional(result.model_dump())

    with open(cfg["output_path"], "w", encoding="utf-8") as f:
        json.dump(result_dict, f, ensure_ascii=False, indent=2)

    print(f"Wrote {len(result.locations)} locations, {len(result.events)} events, "
          f"{len(result.relationships)} relationships to {cfg['output_path']}")
    if result.unmatched_characters:
        print(f"\n{len(result.unmatched_characters)} unmatched character(s) flagged for review:")
        for uc in result.unmatched_characters:
            print(f"  - {uc.name_in_text}: {uc.note}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(f"Usage: python {sys.argv[0]} <{'|'.join(BATCHES)}>")
    run_batch(sys.argv[1])
